name: update another repo

on: [push]

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout Project A
          uses: actions/checkout@v3
          with:
            path: ./repo-update

        - name: Checkout Project B
          uses: actions/checkout@v3
          with: 
            repository: tomassirio/argo
            token: ${{ secrets.TOKEN }}
            path: ./argo
            ref: main

        - name: Copy/Create file
          run: |
            FILE=./repo-update/file
            if [ -f "$FILE" ]; then
              echo "Copying $FILE"
              cp -R ./repo-update/file ./argo
            else 
              echo "Creating $FILE"
              touch ./argo/file
            fi

        - name: Push Project B
          run: |
            cd ./argo
            git add .
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "File Replicated from Project A"
            git push