name: update another repo

on: [push]

jobs:
    replicate-file:
        runs-on: ubuntu-latest
        name: Replicate File

        steps:
        - name: Checkout Project repo-update
          uses: actions/checkout@v3
          with:
            persist-credentials: false


        - name: Checkout Project B
          uses: actions/checkout@v3
          with: 
            repository: shyamayadav154/argo
            token: ${{ secrets.TOKEN }}
            path: ./argo
            ref: main
            persist-credentials: true

        

        - name: Push Project argo
          run: |
            echo $GITHUB_SHA
            cd ./argo
            cd k8
            ls
            cat frontend.yml
            sed -i "s|image: .*|image: $GITHUB_SHA|g" deployment.yml
            cat frontend.yml
            touch test.txt
            git status
            git add ..
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -am "File Replicated from Project A"
            git push